### ISSUE TITLE
API-Manager REST API failure

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2/product-vick#137]
**Description:**
Sample employee-portal fails while trying to connect to API manager. This leads to fail API microgateway initialization. 

Error: employee--gateway-deployment-7d4dd9cb58-5vb62        0/1       Init:CrashLoopBackOff

**Suggested Labels:**
APIM

**Suggested Assignees:**
N/A

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
kubectl apply -f https://raw.githubusercontent.com/wso2/product-vick/master/samples/employee-portal/artifacts/sample-hr-cell.yaml

**Related Issues:**
N/A

**Comment by sinthuja** [comment]
This issue is not there anymore. This should be an intermediate issue. Therefore, I'm closing this issue. Please reopen if it's encountered again.
