### ISSUE TITLE
Support for "external" cells

### ISSUE THREAD

**Issue by afkham** [wso2/product-vick#144]
**Description:**
In the cell architecture white paper, we model everything including external APIs, legacy systems, etc as cells. We need to have a separate "external" cell type that will support this. Things like the docker image, replicas etc do no make sense for this kind of cells. The external APIs, security policies etc will be parts of these cell descriptions. This allows a uniform way to model the system and register cells.

**Comment by Mirage20** [comment]
From the implementation perspective, this is more similar to K8s service with ExternalName[1] type. Will do some research to bring this into the cell-based architecture. 
[1] https://kubernetes.io/docs/concepts/services-networking/service/#externalname

**Comment by sinthuja** [comment]
Create an issue https://github.com/wso2-cellery/sdk/issues/143 to track this.
