### ISSUE TITLE
Rename the WSO2 VICK Observability to something like Cellery Observability

### ISSUE THREAD

**Issue by sinthuja** [wso2/product-vick#225]
**Description:**
Currently we have used term WSO2 VICK in the title page, but VICK is only used for internal purpose. Therefore let's change this name to Cellery.

**Comment by Minoli** [comment]
FIxed with https://github.com/wso2/product-vick/pull/230/commits/64c8694c9c01b68eec69ad3928b29daabbdc886c

**Comment by nadundesilva** [comment]
Closing as per the above comment.
