### ISSUE TITLE
wso2sp-worker is CrashLoopBackOff

### ISSUE THREAD

**Issue by tongsrv** [wso2/product-vick#99]
pod's log:
# kubectl logs -p wso2sp-worker-7fb486767-48ltt -n vick-system
/home/wso2carbon/wso2sp-4.3.0/bin/worker.sh: 65: /home/wso2carbon/wso2sp-4.3.0/bin/worker.sh: /home/wso2carbon/wso2sp-4.3.0/wso2/worker/bin/carbon.sh: not found

**Comment by mefarazath** [comment]
Hi @tongsrv,

Can you explain the steps you followed?

**Comment by tongsrv** [comment]
We use this script - system\scripts\kubeadm\kubeadm-setup.sh

**Comment by sinthuja** [comment]
Hi @tongsrv ,

We have done further improvements for this and this problem should not be there anymore. You can try the script found in [https://github.com/wso2/product-vick/tree/master/system/scripts/all-in-one-installer](https://github.com/wso2/product-vick/tree/master/system/scripts/all-in-one-installer) to install. 

Thanks,
Sinthuja.
